created HTML and SCSS structure for the components
gribVolnushka/H-legals pull request #1
Opened 2022-12-10 13:09 UTC by gribVolnushka

2022-12-11 17:52 UTC, Rammfall requested changes

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Mixins/typografy-mixin.scss
> +@mixin fonts-100() {
font-body
font-small
font-head
font-title
font-mega

2022-12-11 17:52 UTC, Rammfall commented on src/scss/custom-properties.css
> +  --main-primary-color: #323264;
Давай слово color будет первым

2022-12-11 17:52 UTC, Rammfall commented on src/scss/general.scss
> +
Контейнер один, только 1320

2022-12-11 17:52 UTC, Rammfall commented on src/scss/general.scss
> +  border-bottom: 1px solid var(--accent-color);
Этот стиль должен быть в шапке

2022-12-11 17:52 UTC, Rammfall commented on src/static/CSS/styles-fonts.css
> +  src: url("../Fonts/TTNorms-Regular.woff2");
```suggestion
  src: url("../Fonts/TTNorms-Regular.woff2") format("woff2");
```

2022-12-11 17:52 UTC, Rammfall commented on src/static/CSS/styles-fonts.css
> +  src: url("../Fonts/TTNorms-Medium.woff2");
```suggestion
  src: url("../Fonts/TTNorms-Medium.woff2") format("woff2");
```

2022-12-11 17:52 UTC, Rammfall commented on src/static/CSS/styles-fonts.css
> +  src: url("../Fonts/TTNorms-Bold.woff2");
```suggestion
  src: url("../Fonts/TTNorms-Bold.woff2") format("woff2");
```

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +    <h1 class='typography__main-title'>
main-title

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +    <h1 class='typography__main-title'>
Все заголовки компоненты(блоки)

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +      <ul class='list-types__unordered-list'>
Список отдельный блок, а не элемент

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +    <a href='' class='link-types__link'>
Также блок, не элемент, отвязать от секции

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +      <li class='clients__item' style='background-color: var(--background-color-hillel)'>
Завернуть доп. ссылкой, скорее всего такие для перехода

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +        <p class='cases__item-text--hover'>
Модификатор без элемента, если не сильно много общего, то другой класс

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +      <li class='cases__item'>
Нужен модификатор для скрытого состояния

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +      <li class='cases__item'>
cases__item - стандартный, а если добавим cases__item--hidden то он скрыт

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +          стягнення на товар і пов'язаних із заставою ризиками.
Добавить иконки обсолютом

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +          стягнення на товар і пов'язаних із заставою ризиками.
На ховере

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +      <li class='experience__item'>
Добавить модификатор выбранного. experience__item--selected
Я бы дополнительно добавил кнопку, по которой мы кликаем

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +<section class='interactive-elements'>
Каждый элемент в этой секции должен быть отдельным бэм блоком

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +    <div class='wrapper__spinner'>
Враппера нет, сделать просто блоком

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +    <div class='slider__wrapper'>
Блок

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +      <li class='footer__item footer__item--first'>
```suggestion
      <li class='footer__item footer__item--address'>
```

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +      <li class='footer__item'>
Добавим модификатор (--with-dot) он будет добавлять паддинг, добавлять точку и позиционировать

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +        <form action='' class='header__form'>
Весь элемент для смены языка сделать отдельным компонентом и блоком

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +    <div class='header__wrapper-content'>
Внутри контейнера будет три элемента. Логотип, header__wrapper-form и навигация и сделать их гридами

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/experience.scss
> +  @include gradient-supersoft();
Если миксин не медик, то давай в начало их кидать

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/experience.scss
> +.experience__List {
```suggestion
.experience__list {
```

2022-12-11 17:52 UTC, Rammfall commented on src/static/index.html
> +    <ul class='experience__List'>
```suggestion
    <ul class='experience__list'>
```

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/experience.scss
> +    border-right: 4px solid var(--main-white-color);
давай будет фоновый цвет

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/experience.scss
> +    -webkit-background-clip: text;
вендорные префиксы в миксин!

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/experience.scss
> +  padding-right: 40px;
Я бы добавил транзишн

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/experience.scss
> +      border-right: 4px solid var(--accent-color);
так же само фон

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/experience.scss
> +  font-weight: 700;
Добавить релатив

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/experience.scss
> +      height: 50px;
Не хардкодить высоту, использовать 100%

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/cases.scss
> +  margin-bottom: 50px;
без маржина

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/cases.scss
> +  border: 1px solid #FFFFFF;
цвет из переменной

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/header.scss
> +
remove empty lines

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/interactive-elements.scss
> +@keyframes ellipse {
```suggestion
@keyframes rotate {
```

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/interactive-elements.scss
> +@keyframes ellipse {
Создать отдельный файл под кейфремс

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/interactive-elements.scss
> +  animation-name: ellipse;
```suggestion
  animation-name: rotate;
```

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/interactive-elements.scss
> +  &:active {
Для эктива так же отдельный модификатор

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/interactive-elements.scss
> +
Удалить лишние линии

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/link.scss
> +.link-types__link {
отдельный компонет

2022-12-11 17:52 UTC, Rammfall commented on src/scss/Components/typography.scss
> +  margin-bottom: 20px;
маржины убрать с компонетов

2022-12-12 22:53 UTC, gribVolnushka commented on src/scss/Mixins/typografy-mixin.scss
> +@mixin fonts-100() {
я пофиксила ошибки

2022-12-20 20:23 UTC, merged